name: autofix.ci

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/autofix-python.yml'
      - 'python/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.head_ref || github.ref_name }} 
  
  # If this is enabled it will cancel the current running and start the latest
  cancel-in-progress: true

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: pipx run ruff check --fix

      - uses: autofix-ci/action@d3e591514b99d0fca6779455ff8338516663f7cc
